<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mezhs.Integration.Abstractions\Mezhs.Integration.Abstractions.csproj" />
    <ProjectReference Include="..\..\transports\Mezhs.Browser.Abstractions\Mezhs.Browser.Abstractions.csproj" />
  </ItemGroup>
</Project>
