$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
function Read([string]$path) { Get-Content (Join-Path $root $path) -Raw }
function Assert([bool]$condition, [string]$message) { if (-not $condition) { throw $message } }

$program = Read "src/Mezhs.Agent.Api/Program.cs"
$config = Read "src/Mezhs.Agent.Api/Configuration/AgentConfigLoader.cs"
$options = Read "src/Mezhs.Agent.Api/Configuration/AgentOptions.cs"
$worker = Read "src/Mezhs.Agent.Api/Services/AgentWorker.cs"
$shell = Read "src/Mezhs.Agent.Api/Commands/Shell.cs"
$store = Read "src/Mezhs.Agent.Api/Persistence/AgentStore.cs"
$models = Read "src/Mezhs.Agent.Api/Models/AgentModels.cs"
$mapper = Read "src/Mezhs.Agent.Api/Models/AgentApiMapper.cs"
$policyContext = Read "src/Mezhs.Agent.Api/Policy/PolicyContext.cs"
$policyDecoder = Read "src/Mezhs.Agent.Api/Policy/PolicyDecoder.cs"
$evaluation = Read "src/Mezhs.Agent.Api/Policy/PolicyEvaluationService.cs"
$agentService = Read "src/Mezhs.Agent.Api/Services/AgentService.cs"
$agentClient = Read "src/Mezhs.Agent.Api.Client/AgentApiClient.cs"
$agentWebHost = Read "src/Mezhs.Agent.Web/Program.cs"
$agentWebApp = Read "src/Mezhs.Agent.Web/src/App.tsx"
$sharedChat = Read "src/Mezhs.Web.Lib/src/ChatSurface.tsx"
$resize = Read "src/Mezhs.Web.Lib/src/useAutoResizeTextArea.ts"
$markdown = Read "src/Mezhs.Web.Lib/src/MarkdownContent.tsx"

Assert ($program -notmatch 'AgentApiAuthentication|MEZHS_AGENT_API_KEY|StatusCodes\.Status401Unauthorized') "Decorative bearer authentication still exists in Agent API."
Assert ($program -notmatch 'AllowAnyOrigin|AllowAnyHeader|AllowAnyMethod|AddCors|UseCors') "Agent API still exposes permissive CORS."
Assert ($config -match 'RequiredLoopbackHttpUri' -and $config -match 'uri\.IsLoopback') "Host-shell Agent API is not restricted to loopback binding."
Assert ($agentWebHost -match 'RequireLoopbackUrls' -and $agentWebHost -match 'RequireLoopbackUri' -and $agentWebHost -match 'builder\.WebHost\.UseUrls') "Agent Web does not enforce its loopback listener boundary."
Assert ($agentWebHost -notmatch 'Authorization|Bearer|MEZHS_AGENT_API_KEY') "Agent Web still carries redundant bearer authentication machinery."
Assert ($options -match 'QueueCapacity' -and $options -match 'MaxConcurrentExecutions' -and $options -match 'Workspace') "Agent runtime capacity/workspace settings are not typed configuration."
Assert ($worker -match 'Channel\.CreateBounded<bool>' -and $worker -match 'SignalWork' -and $worker -notmatch 'Channel\.CreateBounded<string>|_queuedCount|_activeCount') "Agent worker still owns execution IDs/state instead of using a wake-only channel."
Assert ($worker -match 'Enumerable\.Range\(0, _maxConcurrentExecutions\)' -and $worker -notmatch 'HashSet<Task>|_chatGates|SemaphoreSlim') "Agent worker concurrency or per-chat serialization remains in transient task/gate state."
Assert ($store -match 'TryCreateRootExecution' -and $store -match 'TryClaimNextQueuedExecution' -and $store -match 'RETURNING \*') "SQLite is not the authoritative admission/claim owner for root executions."
Assert ($store -match 'NOT EXISTS \(' -and $store -match 'active\.ChatId = queued\.ChatId') "Queued same-chat work is not serialized before becoming Running."
Assert ($store -notmatch 'Cache\s*=\s*SqliteCacheMode\.Shared') "AgentStore still combines SQLite shared-cache mode with WAL."
Assert ($shell -match 'WorkingDirectory = options\.Workspace' -and $shell -match 'RedirectStandardInput = true') "Shell workspace/input ownership is missing."
Assert ($shell -notmatch 'GetTempPath|\.cmd"|TryDelete') "Shell still depends on temporary command files."
Assert ($shell -match 'Kill\(entireProcessTree: true\)' -and $shell -match 'CancelAfter\(context\.Timeout\)') "Shell timeout does not own process-tree termination."
Assert ($agentService -match 'Policy does not allow environment variable' -and $agentService -match 'StartsWith\("MEZHS_"') "Caller environment variables are not policy-scoped/reserved."
Assert ($agentService -match 'QueueCapacity.*MaxConcurrentExecutions' -and $agentService -match 'TryCreateRootExecution' -and $agentService -match 'SignalWork') "Admission is not coupled to durable queue capacity and worker wake-up."
Assert ($store -notmatch '_writeLock') "AgentStore still serializes all writes through one application lock."
Assert ($store -match 'TriggerMessageId' -and $store -match 'CommandIndex') "Durable command identity is missing from execution persistence."
Assert ($models -match 'CancelRequested' -and $store -match 'RequestCancel' -and $store -match 'CompleteCancellation') "Cancellation acknowledgement state is not represented durably."
Assert ($mapper -match 'AgentExecutionView' -and $program -match 'AgentApiMapper\.ToView') "Persistence records are still exposed directly through execution endpoints."
Assert ($policyContext -match 'ExecutionEvidence' -and $evaluation -match 'Select\(ToEvidence\)') "Policy evaluation does not consume immutable evidence snapshots."
Assert ($policyContext -match 'CommandDefinition Command' -and $policyContext -notmatch 'string Kind,\s*string Request') "Policy actions remain opaque string kind/request pairs."
Assert ($policyDecoder -match 'RequiredSuccessfulCommands' -and $policyDecoder -match 'AgentExecutionStatus\.Completed') "Completion cannot require successful command evidence."
Assert ($program -notmatch '/v1/metrics|AgentMetrics' -and $evaluation -notmatch 'AgentMetrics' -and $agentClient -notmatch 'GetMetricsAsync|AgentMetricsView') "Unused Agent metrics infrastructure still exists."
Assert ($program -notmatch 'X-MEZHS-Requester|GetRequester|Requester' -and $agentWebHost -notmatch 'X-MEZHS-Requester|Requester' -and $agentClient -notmatch 'X-MEZHS-Requester|Requester') "Unauthenticated requester provenance still exists at API boundaries."
Assert ($models -notmatch '\bRequester\b' -and $store -notmatch '\bRequester\b' -and $shell -notmatch 'MEZHS_REQUESTER|\.Requester' -and $agentWebApp -notmatch '\brequester\b') "Requester residue remains in persistence, shell context, or dashboard."
Assert ($sharedChat -match 'MarkdownContent' -and $markdown -match 'safeLink') "Shared chat rendering does not own safe Markdown presentation."
Assert ($resize -match 'useLayoutEffect' -and $resize -notmatch 'useEffect') "Composer resize still occurs after paint."

Write-Host "PASS: Agent ownership boundaries cover local-only exposure, durable SQLite admission/claiming, same-chat serialization, cancellation, workspace shell execution, DTOs, completion evidence, and shared UI behavior."
