$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
function Read([string]$path) { Get-Content (Join-Path $root $path) -Raw }
function Assert([bool]$condition, [string]$message) { if (-not $condition) { throw $message } }

$program = Read "src/Mezhs.Agent.Api/Program.cs"
$config = Read "src/Mezhs.Agent.Api/Configuration/AgentConfigLoader.cs"
$options = Read "src/Mezhs.Agent.Api/Configuration/AgentOptions.cs"
$worker = Read "src/Mezhs.Agent.Api/Services/AgentWorker.cs"
$shell = Read "src/Mezhs.Agent.Api/Commands/Shell.cs"
$store = Read "src/Mezhs.Agent.Api/Persistence/AgentStore.cs"
$models = Read "src/Mezhs.Agent.Api/Models/AgentModels.cs"
$mapper = Read "src/Mezhs.Agent.Api/Models/AgentApiMapper.cs"
$policyContext = Read "src/Mezhs.Agent.Api/Policy/PolicyContext.cs"
$policyDecoder = Read "src/Mezhs.Agent.Api/Policy/PolicyDecoder.cs"
$evaluation = Read "src/Mezhs.Agent.Api/Policy/PolicyEvaluationService.cs"
$agentService = Read "src/Mezhs.Agent.Api/Services/AgentService.cs"
$agentWebHost = Read "src/Mezhs.Agent.Web/Program.cs"
$sharedChat = Read "src/Mezhs.Web.Lib/src/ChatSurface.tsx"
$resize = Read "src/Mezhs.Web.Lib/src/useAutoResizeTextArea.ts"
$markdown = Read "src/Mezhs.Web.Lib/src/MarkdownContent.tsx"

Assert ($program -notmatch 'AgentApiAuthentication|MEZHS_AGENT_API_KEY|StatusCodes\.Status401Unauthorized') "Decorative bearer authentication still exists in Agent API."
Assert ($program -notmatch 'AllowAnyOrigin|AllowAnyHeader|AllowAnyMethod|AddCors|UseCors') "Agent API still exposes permissive CORS."
Assert ($config -match 'RequiredLoopbackHttpUri' -and $config -match 'uri\.IsLoopback') "Host-shell Agent API is not restricted to loopback binding."
Assert ($agentWebHost -match 'RequireLoopbackUrls' -and $agentWebHost -match 'RequireLoopbackUri' -and $agentWebHost -match 'builder\.WebHost\.UseUrls') "Agent Web does not enforce its loopback listener boundary."
Assert ($agentWebHost -notmatch 'Authorization|Bearer|MEZHS_AGENT_API_KEY') "Agent Web still carries redundant bearer authentication machinery."
Assert ($agentWebHost -match 'X-MEZHS-Requester' -and $agentWebHost -match 'agent-web') "Agent Web no longer records proxy requester provenance."
Assert ($options -match 'QueueCapacity' -and $options -match 'MaxConcurrentExecutions' -and $options -match 'Workspace') "Agent runtime capacity/workspace settings are not typed configuration."
Assert ($worker -match 'Channel\.CreateBounded<string>' -and $worker -notmatch 'CreateUnbounded') "Agent worker queue is not bounded."
Assert ($worker -match 'Enumerable\.Range\(0, _maxConcurrentExecutions\)' -and $worker -notmatch 'HashSet<Task>') "Agent worker does not use fixed owned consumers for concurrency."
Assert ($shell -match 'WorkingDirectory = options\.Workspace' -and $shell -match 'RedirectStandardInput = true') "Shell workspace/input ownership is missing."
Assert ($shell -notmatch 'GetTempPath|\.cmd"|TryDelete') "Shell still depends on temporary command files."
Assert ($shell -match 'Kill\(entireProcessTree: true\)' -and $shell -match 'CancelAfter\(context\.Timeout\)') "Shell timeout does not own process-tree termination."
Assert ($agentService -match 'Policy does not allow environment variable' -and $agentService -match 'StartsWith\("MEZHS_"') "Caller environment variables are not policy-scoped/reserved."
Assert ($store -notmatch '_writeLock') "AgentStore still serializes all writes through one application lock."
Assert ($store -match 'TriggerMessageId' -and $store -match 'CommandIndex' -and $store -match 'Requester') "Durable command/requester identity is missing from execution persistence."
Assert ($models -match 'CancelRequested' -and $store -match 'RequestCancel' -and $store -match 'CompleteCancellation') "Cancellation acknowledgement state is not represented durably."
Assert ($mapper -match 'AgentExecutionView' -and $program -match 'AgentApiMapper\.ToView') "Persistence records are still exposed directly through execution endpoints."
Assert ($policyContext -match 'ExecutionEvidence' -and $evaluation -match 'Select\(ToEvidence\)') "Policy evaluation does not consume immutable evidence snapshots."
Assert ($policyContext -match 'CommandDefinition Command' -and $policyContext -notmatch 'string Kind,\s*string Request') "Policy actions remain opaque string kind/request pairs."
Assert ($policyDecoder -match 'RequiredSuccessfulCommands' -and $policyDecoder -match 'AgentExecutionStatus\.Completed') "Completion cannot require successful command evidence."
Assert ($program -match '/v1/metrics' -and $program -match 'PolicyDenials') "Operational Agent metrics are not exposed."
Assert ($sharedChat -match 'MarkdownContent' -and $markdown -match 'safeLink') "Shared chat rendering does not own safe Markdown presentation."
Assert ($resize -match 'useLayoutEffect' -and $resize -notmatch 'useEffect') "Composer resize still occurs after paint."

Write-Host "PASS: Agent ownership boundaries cover local-only exposure, bounded concurrency, durable evidence, cancellation, workspace shell execution, DTOs, metrics, and shared UI behavior."
