$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
function Read([string]$path) { Get-Content (Join-Path $root $path) -Raw }
function Assert([bool]$condition, [string]$message) { if (-not $condition) { throw $message } }

$program = Read "src/Mezhs.Agent.Api/Program.cs"
$config = Read "src/Mezhs.Agent.Api/Configuration/AgentConfigLoader.cs"
$options = Read "src/Mezhs.Agent.Api/Configuration/AgentOptions.cs"
$worker = Read "src/Mezhs.Agent.Api/Services/AgentWorker.cs"
$recovery = Read "src/Mezhs.Agent.Api/Services/AgentRecoveryState.cs"
$shell = Read "src/Mezhs.Agent.Api/Commands/Shell.cs"
$store = Read "src/Mezhs.Agent.Api/Persistence/AgentStore.cs"
$models = Read "src/Mezhs.Agent.Api/Models/AgentModels.cs"
$mapper = Read "src/Mezhs.Agent.Api/Models/AgentApiMapper.cs"
$policyContext = Read "src/Mezhs.Agent.Api/Policy/PolicyContext.cs"
$policyDecoder = Read "src/Mezhs.Agent.Api/Policy/PolicyDecoder.cs"
$evaluation = Read "src/Mezhs.Agent.Api/Policy/PolicyEvaluationService.cs"
$agentService = Read "src/Mezhs.Agent.Api/Services/AgentService.cs"
$agentClient = Read "src/Mezhs.Agent.Api.Client/AgentApiClient.cs"
$agentWebHost = Read "src/Mezhs.Agent.Web/Program.cs"
$agentWebApp = Read "src/Mezhs.Agent.Web/src/App.tsx"
$executorStore = Read "src/Mezhs.Executor/ExecutorStore.cs"
$executorRunner = Read "src/Mezhs.Executor/ExecutorRunner.cs"
$executorService = Read "src/Mezhs.Executor/ExecutorService.cs"
$sqlite = Read "src/Mezhs.Sqlite/SqliteDatabase.cs"
$sharedChat = Read "src/Mezhs.Web.Lib/src/ChatSurface.tsx"
$resize = Read "src/Mezhs.Web.Lib/src/useAutoResizeTextArea.ts"
$markdown = Read "src/Mezhs.Web.Lib/src/MarkdownContent.tsx"

Assert ($program -notmatch 'AgentApiAuthentication|MEZHS_AGENT_API_KEY|StatusCodes\.Status401Unauthorized') "Decorative bearer authentication still exists in Agent API."
Assert ($program -notmatch 'AllowAnyOrigin|AllowAnyHeader|AllowAnyMethod|AddCors|UseCors') "Agent API still exposes permissive CORS."
Assert ($config -match 'RequiredLoopbackHttpUri' -and $config -match 'uri\.IsLoopback') "Host-shell Agent API is not restricted to loopback binding."
Assert ($agentWebHost -match 'RequireLoopbackUrls' -and $agentWebHost -match 'RequireLoopbackUri' -and $agentWebHost -match 'builder\.WebHost\.UseUrls') "Agent Web does not enforce its loopback listener boundary."
Assert ($agentWebHost -notmatch 'Authorization|Bearer|MEZHS_AGENT_API_KEY') "Agent Web still carries redundant bearer authentication machinery."
Assert ($options -match 'QueueCapacity' -and $options -match 'MaxConcurrentExecutions' -and $options -match 'Workspace') "Agent runtime capacity/workspace settings are not typed configuration."

Assert ($worker -match 'Channel\.CreateBounded<bool>' -and $worker -match 'SignalWork' -and $worker -notmatch 'Channel\.CreateBounded<string>|_queuedCount|_activeCount') "Agent worker still owns execution IDs/state instead of using a wake-only channel."
Assert ($worker -match 'Enumerable\.Range\(0, _maxConcurrentExecutions\)' -and $worker -notmatch 'HashSet<Task>|_chatGates|SemaphoreSlim') "Agent worker concurrency or per-chat serialization remains in transient task/gate state."
Assert ($store -match 'TryCreateRootExecution' -and $store -match 'TryClaimNextQueuedExecution' -and $store -match 'RETURNING \*') "SQLite is not the authoritative admission/claim owner for root Agent executions."
Assert ($store -match 'NOT EXISTS \(' -and $store -match 'active\.ChatId = queued\.ChatId') "Queued same-chat work is not serialized before becoming Running."
Assert ($agentService -match 'QueueCapacity.*MaxConcurrentExecutions' -and $agentService -match 'TryCreateRootExecution' -and $agentService -match 'SignalWork') "Admission is not coupled to durable queue capacity and worker wake-up."
Assert ($models -match 'CancelRequested' -and $store -match 'RequestCancel' -and $store -match 'CompleteCancellation') "Cancellation acknowledgement state is not represented durably."
Assert ($worker -match 'Only root Agent executions can be cancelled directly' -and $worker -match '_executor\.Kill') "Root Agent cancellation does not own cancellation of its active Executor children."

Assert ($shell -match 'executor\.Execute' -and $shell -match 'executor\.WaitAsync' -and $shell -match 'options\.Workspace') "Agent shell commands are not routed through Executor with the configured workspace."
Assert ($shell -notmatch 'ProcessStartInfo|Process\.Start|Kill\(|CancelAfter|GetTempPath|\.cmd"|TryDelete|ShellTerminationException') "Agent shell layer still owns direct process lifecycle mechanics."
Assert ($executorRunner -match 'ProcessStartInfo' -and $executorRunner -match 'RedirectStandardInput = true') "Executor does not own host shell process creation/input."
Assert ($executorRunner -match 'Kill\(entireProcessTree: true\)' -and $executorRunner -match 'TimeoutSeconds') "Executor does not own process-tree termination and timeout."
Assert ($executorRunner -match 'termination was not confirmed|termination could not be confirmed' -and $executorRunner -match 'ExecutionStatus\.Failed') "Executor termination uncertainty can still become a normal terminal success state."
Assert ($executorStore -match 'UX_ExecutorExecutions_AgentCommand' -and $executorStore -match 'TriggerMessageId' -and $executorStore -match 'CommandIndex') "Executor durable command identity/idempotency is missing."
Assert ($program -match '/v1/executions/\{executionId\}/kill' -and $program -match '/v1/executions/\{executionId\}/restart' -and $program -match 'use /kill') "Agent API does not separate root cancel from Executor kill/restart."
Assert ($agentWebApp -match 'Kill' -and $agentWebApp -match 'Restart' -and $agentWebApp -match 'restartedFromId|restartedAsId') "Agent dashboard does not expose Executor lifecycle controls/lineage."

Assert ($sqlite -match 'class SqliteDatabase' -and $sqlite -match 'journal_mode=WAL' -and $sqlite -match 'busy_timeout' -and $sqlite -match 'EnsureColumn' -and $sqlite -match 'DropColumnIfExists') "Shared SQLite foundation does not own common path/connection/migration mechanics."
Assert ($store -match 'SqliteDatabase _database' -and $store -notmatch 'new SqliteConnectionStringBuilder|private SqliteConnection Open\(') "AgentStore still duplicates SQLite connection ownership."
Assert ($recovery -match 'new SqliteDatabase' -and $recovery -match 'SqliteDatabase\.TableExists' -and $recovery -notmatch 'new SqliteConnectionStringBuilder') "Agent restart recovery bypasses the shared SQLite foundation."
Assert ($executorStore -match 'SqliteDatabase _database' -and $executorStore -notmatch 'new SqliteConnectionStringBuilder') "ExecutorStore bypasses the shared SQLite foundation."
Assert ($store -notmatch 'CreateChildExecution|CompleteShell|FailShell|TryMarkRunning|public bool Interrupt') "AgentStore still exposes obsolete shell execution persistence paths."
Assert ($store -notmatch '_writeLock|Cache\s*=\s*SqliteCacheMode\.Shared') "AgentStore still carries obsolete application locking/shared-cache behavior."
Assert ($store -match 'SqliteDatabase\.DropColumnIfExists\(connection, "Executions", "Requester"\)') "Legacy requester column is not cleaned up during schema migration."

Assert ($policyContext -match 'ExecutionEvidence' -and $evaluation -match 'executor\.List' -and $evaluation -match 'AgentExecutionKind\.Shell') "Policy evaluation does not combine immutable Agent and Executor evidence."
Assert ($evaluation -match 'Registry\.Get\(CommandBehavior\.Shell\)\.Name' -and $policyDecoder -match 'RequiredSuccessfulCommands' -and $policyDecoder -match 'AgentExecutionStatus\.Completed') "Successful Executor shell evidence cannot satisfy completion requirements."
Assert ($policyContext -match 'CommandDefinition Command' -and $policyContext -notmatch 'string Kind,\s*string Request') "Policy actions remain opaque string kind/request pairs."
Assert ($mapper -match 'AgentExecutionView' -and $program -match 'AgentApiMapper\.ToView') "Persistence records are still exposed directly through execution endpoints."

Assert ($agentService -match 'Policy does not allow environment variable' -and $agentService -match 'StartsWith\("MEZHS_"') "Caller environment variables are not policy-scoped/reserved."
Assert ($program -notmatch '/v1/metrics|AgentMetrics' -and $evaluation -notmatch 'AgentMetrics' -and $agentClient -notmatch 'GetMetricsAsync|AgentMetricsView') "Unused Agent metrics infrastructure still exists."
Assert ($program -notmatch 'X-MEZHS-Requester|GetRequester|Requester' -and $agentWebHost -notmatch 'X-MEZHS-Requester|Requester' -and $agentClient -notmatch 'X-MEZHS-Requester|Requester') "Unauthenticated requester provenance still exists at API boundaries."
Assert ($models -notmatch '\bRequester\b' -and $store -notmatch 'Requester TEXT|\$requester|record\.Requester|GetOrdinal\("Requester"\)' -and $shell -notmatch 'MEZHS_REQUESTER|\.Requester' -and $agentWebApp -notmatch '\brequester\b') "Requester residue remains in persistence, shell context, or dashboard."
Assert ($sharedChat -match 'MarkdownContent' -and $markdown -match 'safeLink') "Shared chat rendering does not own safe Markdown presentation."
Assert ($resize -match 'useLayoutEffect' -and $resize -notmatch 'useEffect') "Composer resize still occurs after paint."

Write-Host "PASS: Agent owns reasoning/admission/cancel, Executor exclusively owns shell/process lifecycle and shell evidence, SQLite mechanics are shared, and UI/API expose one combined execution view."
