<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Mezhs.Integration.Browser\Mezhs.Integration.Browser.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="browser\gemini.ts" LogicalName="Mezhs.Integrations.Gemini.BrowserModule" />
  </ItemGroup>
</Project>
